### ISSUE TITLE
Avoid recommending curl bash piping

### ISSUE THREAD

**Issue by q0rban** [Lullabot/drupal8ci#1]
[Piping curl to bash is an anti-pattern](https://news.ycombinator.com/item?id=12766049). Is there a way we could avoid it? Could we have this be a package that you `composer require` instead?

If there's not a way to avoid it, we should at least wrap everything this script does in a function and then execute the function at the end. That way if the stream is interrupted, the partial script isn't executed.

**Comment by juampynr** [comment]
@deviantintegral is my security master, and he does the same thing at https://github.com/deviantintegral/drupal_tests.

We could turn this into a [Robo collection](http://robo.li/collections/), which would on one hand give us a lot of control over errors and on the other better feedback to users. Thoughts?

**Comment by deviantintegral** [comment]
I think the security side is covered as long as we're downloading over https. At that point, piping to the shell is not really different than downloading and running `./install.sh`.

I'd never seen the interrupted pipe scenario before. That's a good one! Thanks for cleaning that up. I've got to use that for https://github.com/deviantintegral/drupal_tests/blob/master/setup.sh

I'm curious about somehow making this a composer package. I guess it would work by defining a custom installation type? I think the scripts section in a composer.json is root-only, so I'm not sure how we'd add and modify files inside of the .circleci directory.

**Comment by juampynr** [comment]
@q0rban do you think that what you did at https://github.com/juampynr/drupal8ci/pull/3 is enough to mark this issue as done?

**Comment by q0rban** [comment]
Yep!
