### ISSUE TITLE
suggestion: wrap codesniffer tests via Robo?

### ISSUE THREAD

**Issue by dakkusingh** [Lullabot/drupal8ci#19]
For a personal project I am using Robo to execute all tests. This is partially how Acquia BLT also uses Robo as a wrapper for tasks. 

The advantage is that you no longer have to configure each CI script should you want to make changes.

Here is an example of what I am proposing:
https://github.com/dakkusingh/drupaltest/blob/master/RoboFile.php#L57

Happy to work on this and make a PR if you agree with this approach.

**Comment by dakkusingh** [comment]
Something like this :)

![screen shot 2018-03-23 at 5 46 23 pm](https://user-images.githubusercontent.com/1692872/37845367-38d3d7f0-2ec2-11e8-8d2e-655efc4b2e5e.png)

**Comment by juampynr** [comment]
@dakkusingh yep! I have been working on this for the Travis CI implementation at [d8cidemo](https://github.com/juampynr/d8cidemo/pull/7) (my pet project to test CI integrations). I plan to port those changes to this repository once I get the behat job passing.

**Comment by juampynr** [comment]
[Ported to this repository](https://github.com/Lullabot/drupal8ci/blob/master/dist/travisci/.travis/RoboFile.php).

The main reason why I used Robo in this way is because it allowed me to use Travis' test matrix and the after_script stage in a clean way. See https://github.com/Lullabot/drupal8ci/blob/master/dist/travisci/.travis.yml.

Next would be to port this approach to [CircleCI's RoboFile](https://github.com/Lullabot/drupal8ci/blob/master/dist/circleci/.circleci/RoboFile.php).

**Comment by dakkusingh** [comment]
@juampynr great work. I had a look this morning :)
On porting CircleCI and Travis, see my food for thought issue https://github.com/Lullabot/drupal8ci/issues/22

**Comment by juampynr** [comment]
[This pull request](https://github.com/Lullabot/drupal8ci/pull/26) moves all the circleci jobs logic to Robo tasks. Now that CircleCI and Travis CI use almost exactly the same RoboFile.php, I am considering moving to it's own repository.

**Comment by dakkusingh** [comment]
Hi @juampynr @deviantintegral a separate repo for Drupal Robo makes a lot of sense. Not only it can be used by drupal8ci & drupal_tests but also anyone requiring a common Robo Lib for their projects.

I had started something similar for my own projects, something similar here would be awesome here.
https://github.com/dakkusingh/robo_drupal

**Comment by deviantintegral** [comment]
I just realized, as long as the CI tool is using a docker container, we can download and put any required RoboFile(s) inside of the container image itself. Is that what you were thinking?

**Comment by dakkusingh** [comment]
I think..
 
**For full projects** (drupalci) its better to download and place the Robofile into the project as part of the setup script. That way, it can also be used for normal day-day operations such as githooks, manually running tests locally etc.

**For module testing**, we can download the Robofile on runtime in the container.

Only caveat is that if the user removes or modifies the Robo functions (in his project repo) and these functions are required by travis / CI - then all tests will start to fail. This wouldnt be a problem for module testing however.

What do you think?

**Comment by guix77** [comment]
Hi, isn't it the case today?

**Comment by juampynr** [comment]
Correct. This was fixed. Closing.
