### ISSUE TITLE
bhat-test failed, why?

### ISSUE THREAD

**Issue by miura** [Lullabot/drupal8ci#23]
Hello, thanks a lot for this quite nice tool. 
I tried installing travis-ti and run it but got an error with bhat-test. Please check here:

https://travis-ci.org/miura/bise/jobs/359122775

here is the last part of the log. Were should I supply URL for wget? I guess I forgot something to set up?

```
0.01s$ cp .travis/RoboFile.php .
0.17s$ vendor/bin/robo $JOB
 [Filesystem\FilesystemStack] mkdir ["mariadb-init"]
 [Exec] Running wget in mariadb-init
wget: missing URL
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.
 [Exec]  Exit code 1  Time 0.01s
 [notice] Stopping on fail. Exiting....
 [error]  Exit Code: 1 
 [error]    in task Robo\Task\Base\Exec 
```

Thanks a lot for your tool and will be looking forward to your advice!

Kota

**Comment by juampynr** [comment]
Hi @miura!

Have a look at this [section of the docs](https://github.com/Lullabot/drupal8ci#setting-up-the-behat-job) and let me know if you have any doubts.

**Comment by miura** [comment]
very clear... I did not scroll down after reading the Travis CI part. I will work on this. Thank you!

**Comment by deviantintegral** [comment]
So this is from not having a drush alias fully configured? I wonder if we can validate that somehow so the error message is more obvious.

**Comment by juampynr** [comment]
@deviantintegral see the task to [download the db in Travis' RoboFile.php](https://github.com/Lullabot/drupal8ci/blob/master/dist/travisci/.travis/RoboFile.php#L85).

I just realized that this is [documented in code for CircleCI](https://github.com/Lullabot/drupal8ci/blob/master/dist/circleci/.circleci/config.yml#L80) but not for Travis CI. I will take the chance to fix that.
