### ISSUE TITLE
Next CI tool?

### ISSUE THREAD

**Issue by juampynr** [Lullabot/drupal8ci#28]
I am inclined to try GitLab CI but any suggestions are welcome.

**Comment by q0rban** [comment]
We already have GitLab CI set up:

- https://github.com/Lullabot/drupal8ci/tree/master/dist/gitlabci
- https://gitlab.com/Lullabot/d8cidemo/pipelines

Or are you meaning that you'd like to get the Behat tests working? I think to do that we'd have to switch to dind.

**Comment by juampynr** [comment]
Yeah, I will look at your GitLab iplementation and see if there is a way to get Behat tests working (I will check out dind). I wanted to leave this open in case anyone suggests other tools too.

**Comment by dakkusingh** [comment]
GitLab CI ++
How about Bitbucket Pipelines?

**Comment by juampynr** [comment]
Hi @dakkusingh! 

He have received a few requests for GitLab so we will do that one next.

**Comment by juampynr** [comment]
Closing. I have updated the installer for GitLab https://github.com/Lullabot/drupal8ci#gitlab-ci.
