### ISSUE TITLE
Out-of-the-box setup doesn't work with drupal-project

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/drupal8ci#29]
The drupal-project template does [not include any of Drupal's require-dev dependencies](https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L29) in it's composer.json. That means that developers setting up a site have to remember to add the dev dependencies like phpunit and the php-unit bridge from [drupal/core's composer.json](https://github.com/drupal/core/blob/8.6.x/composer.json#L53).

I'd suggest that we add all of core's require-dev lines to each setup script, as I think worst case it will just be a no-op.

**Comment by davereid** [comment]
I would recommend requiring drupal/core-dev instead of the individual dependencies.
