### ISSUE TITLE
Issue with setup-gitlab-ci.sh

### ISSUE THREAD

**Issue by visabhishek** [Lullabot/drupal8ci#30]
Problem with "Installation request for drupal/drupal-extension master-dev" while trying to run
`curl -L https://github.com/lullabot/drupal8ci/raw/master/setup-gitlab-ci.sh | bash

![screenshot from 2018-05-18 18-13-18](https://user-images.githubusercontent.com/2493261/40235277-6ad70138-5ac7-11e8-9f00-abc6e2bd936f.png)

`

**Comment by visabhishek** [comment]
Once I update 
`drupal/drupal-extension:master-dev`
to 
`"drupal/drupal-extension:^v4.0.0alpha3"`

then I am able to run the command. please guide me to fix this.

**Comment by deviantintegral** [comment]
We should probably update the setup script to require `^4.0` now that there are alpha tags.

**Comment by visabhishek** [comment]
Issue fixed with https://github.com/Lullabot/drupal8ci/commit/4fa7bc913c40daf77c9f31f7df2172b9e3a8f7a4
