### ISSUE TITLE
I keep getting error about Selenuim Server not being active

### ISSUE THREAD

**Issue by isbkch** [Lullabot/drupal8ci#34]
The error is `The Selenium Server is not active on host http://localhost/wd/hub at port 4444`

Btw, since Selenium driver is being installed in a different container, why is localhost used for the host?

**Comment by juampynr** [comment]
Hi @isbkch! Which CI provider are you using?

Containers are usually connected together via ports. That is why port 4444 is used.

**Comment by isbkch** [comment]
I'm using circleCI

**Comment by juampynr** [comment]
That's weird. I can only suggest that you restart the job with SSH so you can jump into the environment and debug what's going on.

**Comment by deviantintegral** [comment]
To answer your question, CircleCI does some magic and makes all exposed ports available on localhost for all containers in a job. So the apache container can access selenium on localhost:4444, and selenium can access apache back on localhost:80.

The only thing I can think of is perhaps a race condition where the selenium server container is slow to start up, but I've never seen that happen in practice.
