### ISSUE TITLE
Functional tests not working

### ISSUE THREAD

**Issue by acha5066** [Lullabot/drupal8ci#35]
By functional tests I mean those extending BrowserTestBase, that sit in the Functional directory. I get the error "cURL error 7: Failed to connect to localhost port 8080: Connection refused". In my phpunit.xml I have set the SIMPLETEST_BASE_URL to http://localhost:8080. It also doesn't work with the default part 80. 

I'm no docker export but I think this means port mapping is not set up, or I'm using the wrong port.

This isn't really a problem since I use Behat for those kind of tests and it's working fine but I have a bunch of drupal console generated functional tests that were failing.

**Comment by juampynr** [comment]
Hi @acha5066,

What CI tool are you using? Travis or CircleCI? Can you paste screenshots or describe further details about your setup and the error?

**Comment by duartegarin** [comment]
Hi @juampynr ,
I'm also facing issues running Drupal PHPUnit Functional tests.

However, the only thing I see on CircleCI is:
"Too long with no output (exceeded 10m0s)"

The tests work fine locally, but it is using a different endpoint. For these I am just using the default (modified for 8.5) phpunit.xml that comes with the installer.

Any thoughts on what might be wrong?
Thanks!

**Comment by duartegarin** [comment]
Actually I just tried a different test (Metatag module) and the error is the same as above:

For example:

```1) Drupal\Tests\metatag\Functional\DefaultTags::testFrontpage
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:149
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:102
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php:43
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:28
/var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php:51
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:326
/var/www/html/web/core/lib/Drupal/Core/Test/HttpClientMiddleware/TestHttpClientMiddleware.php:31
/var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php:37
/var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php:36
/var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php:54
/var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php:60
/var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php:67
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:277
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:125
/var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:131
/var/www/html/vendor/fabpot/goutte/Goutte/Client.php:180
/var/www/html/vendor/symfony/browser-kit/Client.php:351
/var/www/html/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php:144
/var/www/html/vendor/behat/mink/src/Session.php:148
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:266
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:246
/var/www/html/web/core/tests/Drupal/Tests/BrowserTestBase.php:391
/var/www/html/web/modules/contrib/metatag/tests/src/Functional/DefaultTags.php:43```

**Comment by duartegarin** [comment]
Managed to get it working, by starting apache before running the phpunit command.
I know have another issue, which is permission denied:

```Exception: User warning: mkdir(): Permission Denied
Drupal\Component\PhpStorage\FileStorage->createDirectory()() (Line: 174)```

**Comment by duartegarin** [comment]
Ended up resolving this by calling phpunit with the web user

**Comment by JakeMilburn** [comment]
Hi. I am having the same problem as the original poster.
Getting the error Failed to connect to localhost port 80 when running functional tests.
Has anyone else found a solution or hit this issue?
Base URL is set in phpunit.xml as
` 
<env name="SIMPLETEST_BASE_URL" value="http://localhost"/>
`
This is running in Circle CI.

**Comment by juampynr** [comment]
Hi @JakeMilburn! Can you open a new issue with the above details plus anything else that may help to pinpoint the reason of the error?

Thanks!

**Comment by welly** [comment]
@JakeMilburn I found that the jobServeDrupal job wasn't being called from either another method in RoboFile.php or  .gitlab-ci as per the default configuration so have added:

` - vendor/bin/robo job:serve-drupal`

to 

drupal9ci:unit_kernel_tests and drupal9ci:code_coverage in .gitlab-ci and now it works. I am getting a different error now but I've made some progress.

**Comment by juampynr** [comment]
Thanks for the update @welly ! Let us know if you need help with the different error that you mentioned.

**Comment by welly** [comment]
One of the problems I found was I was getting mkdir() permission denied errors when running functional tests and code coverage reports. I forget where I found a suggested solution for the issue but in runUnitTests()

`
    $tasks[] = $this->taskExecStack()
      ->exec('chmod -R 777 ../web/sites')
      ->envVars(['XDEBUG_MODE' => 'coverage', 'APACHE_RUN_USER' => 'root', 'APACHE_RUN_GROUP' => 'root'] + getenv())
      ->dir('web')
      ->exec('sudo -u root -E sudo -u www-data ../vendor/bin/phpunit -c core --verbose modules/custom');
`

seemed to fix it. I'm not sure if it's the perfect/ideal fix but it does seem to work. I had to do something similar for runCoverageReport() as well.

**Comment by juampynr** [comment]
I think that's fine, this is an isolated environment that runs temporarily.
