### ISSUE TITLE
Multisite recommendations

### ISSUE THREAD

**Issue by MichaelMallett** [Lullabot/drupal8ci#37]
I'm currently working on a way to alter the default installation to work with our multisite. Ill attempt to contribute back here, but if anyone has some recommendations before I start hacking away that would be very useful

**Comment by juampynr** [comment]
Hi @MichaelMallett! Did you have any luck with that? We did this lately with a previous project by doing the following:

* Adding extra statements to install both sites (it was a multisite with just two sites).
* Splitting the jobs in two so there would be for example a Behat job for site a and Behat job for site b.
