### ISSUE TITLE
Could not scan for classes inside vendor/drupal/core/lib/Drupal/

### ISSUE THREAD

**Issue by stuartabrown** [Lullabot/drupal8ci#39]
Hi,

I have created a Drupal 8 BLT project following the documentation at https://blt.readthedocs.io/en/latest/creating-new-project/ and am now trying to run `curl -L https://github.com/lullabot/drupal8ci/raw/master/setup-circleci.sh | bash` to set up CircleCI.  However when I do I get the following errors:

```
Could not scan for classes inside "/Library/WebServer/Documents/my-project/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Library/WebServer/Documents/my-project/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Library/WebServer/Documents/my-project/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be afile nor a folder
```

When I look at my project's directory structure there is no `vendor/drupal/core` but there is`/Library/WebServer/Documents/my-project/**docroot**/core/lib/Drupal/Component` etc

Is there something wrong with my setup or does something need modifying on this CircleCi script?

**Comment by q0rban** [comment]
Most of drupal8ci assumes your Drupal root is in `/web` not `/docroot`. You might be able to get around that by creating a symlink from docroot to web in the repo root. I'm not sure that will resolve your issue here, however, as it seems like something else may be going on, but it's worth a shot.
