### ISSUE TITLE
Error reading Debian Buster package list

### ISSUE THREAD

**Issue by brunodbo** [Lullabot/drupal8ci#44]
I started getting an error when running `apt-get update -y` in GitLab CI, using the `drupal8ci` image. I'm wondering if anyone else is seeing this, since it seems unrelated to GitLab (someone else was able reproduce the error when pulling the image from Docker directly):

```
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:2 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [492 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster InRelease [163 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:9 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [1132 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:11 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages.diff/Index [9592 B]
Get:12 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages.diff/Index [27.9 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages.diff/Index [27.9 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [31.7 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Reading package lists...
E: Could not open file /var/lib/apt/lists/deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)
ERROR: Job failed: exit code 1
```

Any idea what could be causing this to start happening all of a sudden? My GitLab CI had been working fine for months. I've tried clearing the runner caches, but no luck.

**Comment by brunodbo** [comment]
As mentioned on https://github.com/romaricp/kit-starter-symfony-4-docker/issues/10, running `rm -rf /var/lib/apt/lists/*` before doing `apt update` does seem to be a workaround. Still wondering why this error happens in the first place. Could it be some caching issue somewhere?

**Comment by juampynr** [comment]
Hi @brunodbo! I have no idea of why you may be experiencing such issue. I have gone through things like that though while I was under a VPN but here you say that this is running at GitLab CI so that may not be related. Is it still happening? Did you figure out anything else?

**Comment by brunodbo** [comment]
@juampynr Thanks for your reply! Unfortunately, I haven't been able to figure out more details about this issue. I also posted about it in GitLab's support tracker (https://gitlab.com/gitlab-com/support-forum/issues/4528#note_177733868), with one other person commenting they experienced the same issue.

In any case, it seems like this isn't related to the drupal8ci image, so closing this.
