### ISSUE TITLE
Evaluate if we can use the official Drupal image

### ISSUE THREAD

**Issue by juampynr** [Lullabot/drupal8ci#7]
@deviantintegral suggested using the official Drupal image. 

I looked at the official image's Dockerfile and verified that it [downloads Drupal core](https://github.com/docker-library/drupal/blob/cdbfea0a45633dbdbec997334cb902405445a49c/8.4/apache/Dockerfile#L42), which is correct for https://github.com/deviantintegral/drupal_tests but not for this repository because there is already a Drupal 8 project. This is the reason why I went ahead using a custom image. However, I  see value in extracting as much as we can from the official image or even better: propose a change so it can be left out.

**Comment by deviantintegral** [comment]
Good idea - for example, we don't currently include the opcache settings which would be useful for behat test performance.

**Comment by juampynr** [comment]
Working on this locally. Will create a pull request tomorrow. So far I am able to reuse the image by removing Drupal from /var/www/html.

**Comment by juampynr** [comment]
Done at https://github.com/Lullabot/drupal8ci/pull/11.
